config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  root 'gallery#home'
  post '/upload', to: 'gallery#upload', as: :upload
  get '/photos/delete/:id', to: 'gallery#delete_photo', as: :delete_photo
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  mount_uploader :image, PhotoUploader

  def image_full
    image.url
  end

  def image_thumb
    image.thumb.url
  end
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :photos
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/gallery_controller.rb
class GalleryController < ApplicationController
  before_action :authenticate_user!

  def home
    @photos = current_user.photos
  end

  def upload
    @photo = Photo.new(photo_params)
    # @photo.image = photo_params[:image]
    @photo.user = current_user
    @photo.save
    redirect_to root_path
  end

  def delete_photo
    @photo = Photo.find(params[:id])
    if current_user.id = @photo.user.id
      @photo.delete
    end
    redirect_to root_path
  end

  private

  def photo_params
    params.require(:photo).permit(:image)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/gallery_helper.rb
module GalleryHelper
end

app/views/gallery/home.html.haml
.container
  .row
    %h1.my-4.text-center.text-lg-left Gallery
  .row.text-center.text-lg-left
    - @photos.each do |photo|
      .col-lg-3.col-md-4.col-xs-6
        = link_to '#', class: 'd-block mb-4 h100', data: { toggle: 'modal', target: '#imageModal', src: photo.image.url, name: photo.image.filename, id: photo.id } do 
          = image_tag photo.image.thumb.url, alt: photo.image.filename, class: 'img-fluid img-thumbnail'
  .row
    = bootstrap_form_for :photo, layout: :horizontal, url: upload_path do |f|
      = f.file_field :image, hide_label: true, class: 'btn btn-secondary btn-file'
      = f.submit 'Upload Photo', class: 'btn btn-primary'


  #imageModal.modal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
    .modal-dialog{:role => "document"}
    .modal-content
      .modal-header
        %h3#modalTitle
        %button.close{"aria-label" => "Close", "data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
      .modal-body
        = image_tag '', id: 'imageModal-photo' 
      .modal-footer
        %button.btn.btn-secondary{"data-dismiss" => "modal", :type => "button"} Close
        = link_to 'Delete', delete_photo_path(0), class: 'btn btn-danger', id: 'delete' 

app/views/layouts/_user_header.html.haml
%ul.nav.nav-pills.float-right
  - if user_signed_in?
    %li.nav-item
      = link_to "Sign out", destroy_user_session_path, :method => :delete, class: 'btn btn-outline-primary'
  -else 
    %li.nav-item
      = link_to "Sign in", new_user_session_path, class: 'btn btn-outline-primary mr-sm-2'
    %li.nav-item
      = link_to "Sign up", new_user_registration_path, class: 'btn btn-outline-primary mr-sm-2'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Photo Gallery
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container-narrow
      .masthead
      = render 'layouts/user_header'
    %h3.muted
      = link_to "Photo Gallery", root_path 
    %hr
    = yield